### ISSUE TITLE
Probable typo in example code snippet

### ISSUE THREAD

**Issue by kjoewill** [learn-co-curriculum/sinatra-dynamic-routes-codealong#26]
I believe that the following code snippet from this code-along has a confusing typo ...
![2018-10-24_08-34-17](https://user-images.githubusercontent.com/5348914/47439791-39248500-d76a-11e8-823d-3609bd0cef0b.jpg)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kjoewill.

We have updated the materials, fixed this code snippet to correctly display _.first_ rather than .find and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
